name: 'Workflow Wait Action'
description: 'Wait and run a workflow after all other workflows are completed'
branding:
  icon: 'aperture'
  color: 'blue'
inputs:
  access_token:
    description: 'Your GitHub Access Token, defaults to: {{ github.token }}'
    default: '${{ github.token }}'
    required: false
  timeout:
    description: 'Action timeout. If in-progress workflows are not completed within the timeout period, the Action will fails the workflow'
    default: '600'
    required: false
  interval:
    description: 'Interval used to refresh the status of the workflows'
    default: '10'
    required: false
  initial_delay:
    description: 'Initial delay used to give minimal time to all workflows to be queued & started'
    default: '30'
    required: false
  workflows:
    description: 'List of workflows to wait for. Must be a multiline string using |'
    default: ''
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
